/**
 * Diza Teknik Servis — Gördit Bilgisayar
 * Copyright © 2024-2026 Gördit Bilgisayar — Zafer GÖRGÜN
 */

import type {
  TeknikServisItem,
  StokParca,
  Teknisyen,
  KasaHareketi,
  FirmaAyarlari,
} from '../types';

export const initialSettings: FirmaAyarlari = {
  firmaAdi: 'Diza Teknik & Güvenlik & Network Bilişim',
  resmiUnvan: 'Gördit Bilgisayar — Zafer GÖRGÜN',
  telefon: '0(324) 233 00 00',
  gsm: '0(541) 608 53 44',
  email: 'bilgi@gorditbilgisayar.com',
  adres: 'İstiklal Caddesi No:42 Akdeniz / MERSİN',
  vergiDairesi: 'Uray Vergi Dairesi',
  vergiNo: '4110293841',
  webSitesi: 'https://www.gorditbilgisayar.com',
  servisSartlariA4: `1. İÇ & DIŞ SERVİS ŞARTLARI: Atölye veya saha/müşteri yerinde yapılan montaj ve onarımlar teslim tutanağı ile kayıt altına alınır.
2. TEKLİF & PROJELENDİRME: Verilen teklifler 15 gün geçerlidir. Müşteri onayı akabinde malzeme tedariği ve montaj randevusu verilir.
3. GARANTİ KAPSAMI: Kurulan güvenlik kamerası, alarm sistemleri, network donanımları ve bilgisayar parçaları 2 YIL resmi distribütör garantisindedir.
4. SAHA / MONTAJ İŞÇİLİĞİ: Firmamız tarafından yapılan montaj, kablolama ve devreye alma işçilikleri 1 YIL servisimiz garantisi altındadır.
5. YEDEKLEME: Bilgisayar, sunucu ve kamera kayıt cihazlarındaki veri yedekleme sorumluluğu müşteriye aittir.`,
  termalSartlar: `* Kamera, Alarm, Network, Yangın ve PC Çözümleri.
* Yapılan montaj ve parça değişimleri garantilidir.
* Diza Yazılım & Gördit Bilgisayar — Zafer GÖRGÜN`,
  servisNoOnEk: 'DZA',
  sonServisNo: 106,
};

export const initialTechnicians: Teknisyen[] = [
  {
    id: 'tech_1',
    adSoyad: 'Zafer GÖRGÜN',
    telefon: '0(541) 608 53 44',
    uzmanlik: 'Sistem & Yazılım & Proje Yöneticisi',
    aktif: true,
  },
  {
    id: 'tech_2',
    adSoyad: 'Murat TEKNİK',
    telefon: '0(532) 111 22 33',
    uzmanlik: 'Kamera & Yangın & Alarm Saha Şefi',
    aktif: true,
  },
  {
    id: 'tech_3',
    adSoyad: 'Caner USTA',
    telefon: '0(535) 444 55 66',
    uzmanlik: 'Network Kablolama & Donanım Uzmanı',
    aktif: true,
  },
];

export const initialParts: StokParca[] = [
  // Kamera
  {
    id: 'stk_1',
    kod: 'CAM-IP-4MP',
    ad: 'Dahua 4MP H.265 IR Gece Görüşlü IP Bullet Kamera',
    kategori: 'Güvenlik Kamerası',
    stokAdedi: 24,
    kritikStok: 6,
    alisFiyati: 1450,
    satisFiyati: 2400,
    kdvOrani: 20,
  },
  {
    id: 'stk_2',
    kod: 'NVR-8CH-POE',
    ad: 'Dahua 8 Kanal 4K Dahili PoE NVR Kayıt Cihazı',
    kategori: 'Güvenlik Kamerası',
    stokAdedi: 5,
    kritikStok: 2,
    alisFiyati: 3800,
    satisFiyati: 5900,
    kdvOrani: 20,
  },
  // Alarm
  {
    id: 'stk_3',
    kod: 'ALM-PAN-GSM',
    ad: 'Paradox SP4000 8 Bölge Hibrit Alarm Paneli + GSM',
    kategori: 'Hırsız Alarm',
    stokAdedi: 8,
    kritikStok: 2,
    alisFiyati: 3200,
    satisFiyati: 4800,
    kdvOrani: 20,
  },
  {
    id: 'stk_4',
    kod: 'ALM-PIR-PET',
    ad: 'Paradox Dijital Evcil Hayvan Algılamaz PIR Dedektör',
    kategori: 'Hırsız Alarm',
    stokAdedi: 30,
    kritikStok: 8,
    alisFiyati: 450,
    satisFiyati: 750,
    kdvOrani: 20,
  },
  // Network
  {
    id: 'stk_5',
    kod: 'NET-SW-16POE',
    ad: 'Ruijie Reyee 16 Port Gigabit Yönetilebilir PoE Switch',
    kategori: 'Network',
    stokAdedi: 4,
    kritikStok: 2,
    alisFiyati: 4200,
    satisFiyati: 6500,
    kdvOrani: 20,
  },
  {
    id: 'stk_6',
    kod: 'NET-KBL-CAT6',
    ad: 'HES Cat6 UTP 23AWG %100 Bakır Data Kablosu (305m Kutu)',
    kategori: 'Network',
    stokAdedi: 12,
    kritikStok: 3,
    alisFiyati: 2900,
    satisFiyati: 4200,
    kdvOrani: 20,
  },
  // Yangın
  {
    id: 'stk_7',
    kod: 'YNG-DMN-OP',
    ad: 'Mavigard Optik Duman Dedektörü + Soketi',
    kategori: 'Yangın Alarm',
    stokAdedi: 18,
    kritikStok: 4,
    alisFiyati: 480,
    satisFiyati: 850,
    kdvOrani: 20,
  },
  // Bilgisayar & Yazılım
  {
    id: 'stk_8',
    kod: 'PC-SSD-1TB',
    ad: 'Samsung 980 1TB NVMe M.2 SSD 3500MB/s',
    kategori: 'Bilgisayar',
    stokAdedi: 10,
    kritikStok: 3,
    alisFiyati: 2200,
    satisFiyati: 3300,
    kdvOrani: 20,
  },
  {
    id: 'stk_9',
    kod: 'SFT-DIZA-MUH',
    ad: 'Diza Yazılım Ticari Ön Muhasebe & E-Fatura Lisansı',
    kategori: 'Yazılım',
    stokAdedi: 99,
    kritikStok: 5,
    alisFiyati: 4000,
    satisFiyati: 8500,
    kdvOrani: 20,
  },
];

export const initialServices: TeknikServisItem[] = [
  // 1. Dış Servis / Güvenlik Kamerası Montajı & Teklifi
  {
    id: 'srv_101',
    servisNo: 'DZA-2026-0101',
    musteriAdSoyad: 'Toros Lojistik & Antrepo A.Ş.',
    musteriTelefon: '0(324) 233 44 55',
    musteriEmail: 'servis@toroslojistik.com',
    musteriAdres: 'Mersin Liman Bölgesi B Kapısı Yanı No:14',
    servisTuru: 'DisServis',
    faaliyetAlani: 'GuvenlikKamerasi',
    islemTuru: 'MontajKurulum',
    teklifDurumu: 'Onaylandi',
    sahaAdresi: 'Toros Lojistik Antrepo Sahası No:14 Akdeniz/Mersin',
    sahaRandevuTarihi: '2026-09-08T09:00:00.000Z',
    sahaEkibi: 'Murat TEKNİK & Caner USTA',
    sahaNotu: 'Antrepo tavan yüksekliği 7 metre, vinç/iskele hazırlandı.',
    cihazTipi: 'IP Kamera / Dome / Bullet',
    markaModel: 'Dahua 16 Kameralı IP Güvenlik Kamera Sistemi',
    seriNoImei: 'DH-NVR-992019481',
    cihazSifresi: 'Admin123!',
    aksesuarlar: ['NVR Kayıt Cihazı', 'Hard Disk (Kayıt Diski)'],
    siviTemasi: false,
    ekranKirik: false,
    cizikVar: false,
    darbeVar: false,
    acilmiyor: false,
    sarjAlmiyor: false,
    asinIsinma: false,
    sesYok: false,
    kameraArizali: false,
    arizaTanimi: 'Lojistik antreposu için 12 adet dış mekan IP bullet, 4 adet iç mekan dome kamera montajı, kablolama ve NVR kurulumu.',
    teknisyenTespit: 'Keşif yapıldı, 600 metre Cat6 kablo çekilecek, 16 port PoE Switch rack kabine yerleştirilecek.',
    yapilanIslemler: 'Kablolama tamamlandı, kameralar buatlı montaj yapıldı. Sabit IP ve mobil izleme ayarları kuruldu.',
    fotograflar: [],
    durum: 'Tamirde',
    atananTeknisyenId: 'tech_2',
    atananTeknisyenAd: 'Murat TEKNİK',
    gelisTarihi: '2026-09-06T08:30:00.000Z',
    satirlar: [
      {
        id: 'ln_1',
        tur: 'Parca',
        tanim: 'Dahua 4MP H.265 IR Gece Görüşlü IP Bullet Kamera (12 Adet)',
        adet: 12,
        birimFiyat: 2400,
        kdvOrani: 20,
        toplamTutar: 28800,
      },
      {
        id: 'ln_2',
        tur: 'Parca',
        tanim: 'Ruijie Reyee 16 Port Gigabit PoE Switch',
        adet: 1,
        birimFiyat: 6500,
        kdvOrani: 20,
        toplamTutar: 6500,
      },
      {
        id: 'ln_3',
        tur: 'Iscilik',
        tanim: '16 Nokta Kamera Montaj, Yapısal Kablolama & Devreye Alma',
        adet: 1,
        birimFiyat: 12000,
        kdvOrani: 20,
        toplamTutar: 12000,
      },
    ],
    iscilikUcreti: 12000,
    parcaUcreti: 35300,
    kdvTutari: 9460,
    indirimTutari: 1760,
    toplamTutar: 55000,
    alinanKapora: 25000,
    kalanTutar: 30000,
    odemeTuru: 'HavaleEFT',
    tahsilEdildi: false,
    garantiKapsaminda: false,
    garantiSuresiAy: 24,
    oncelik: 'Acil',
    dahiliNotlar: 'Saha montajı devam ediyor, yarın test edilecek.',
  },

  // 2. Dış Servis / Yangın Alarm & İhbar Arıza Çözümü
  {
    id: 'srv_102',
    servisNo: 'DZA-2026-0102',
    musteriAdSoyad: 'Kuzey Tekstil Fabrikası',
    musteriTelefon: '0(542) 678 90 12',
    musteriEmail: 'muhasebe@kuzeytekstil.com',
    musteriAdres: 'Mersin Tarsus Organize Sanayi Bölgesi 4. Cad. No:8',
    servisTuru: 'DisServis',
    faaliyetAlani: 'YanginAlarm',
    islemTuru: 'ArizaCozum',
    sahaAdresi: 'Organize Sanayi Bölgesi 4. Cad. No:8',
    sahaRandevuTarihi: '2026-09-07T11:00:00.000Z',
    sahaEkibi: 'Zafer GÖRGÜN & Murat TEKNİK',
    cihazTipi: 'Konvansiyonel / Adresli Yangın Paneli',
    markaModel: 'Mavigard 8 Bölge Yangın Algılama Sistemi',
    seriNoImei: 'MVG-PAN-8812',
    aksesuarlar: ['Panel Anahtarı', 'Yedek Akü'],
    siviTemasi: false,
    ekranKirik: false,
    cizikVar: false,
    darbeVar: false,
    acilmiyor: false,
    sarjAlmiyor: false,
    asinIsinma: false,
    sesYok: false,
    kameraArizali: false,
    arizaTanimi: 'Fabrika dokuma hattındaki Bölge 3 duman dedektörleri sürekli yangın ihbarı verip sireni çaldırıyor, panel resetlenmiyor.',
    teknisyenTespit: 'İplik tozu ve nem sebebiyle 2 adet optik duman dedektörü kirlenmiş ve loop hattında hat sonu direnci gevşemiş.',
    yapilanIslemler: 'Arızalı 2 adet duman dedektörü yenisiyle değiştirildi, loop hattı ölçüldü, yangın tatbikat siren testi yapıldı.',
    fotograflar: [],
    durum: 'Tamamlandi',
    atananTeknisyenId: 'tech_1',
    atananTeknisyenAd: 'Zafer GÖRGÜN',
    gelisTarihi: '2026-09-07T08:15:00.000Z',
    tamamlanmaTarihi: '2026-09-07T14:30:00.000Z',
    satirlar: [
      {
        id: 'ln_4',
        tur: 'Parca',
        tanim: 'Mavigard Optik Duman Dedektörü (2 Adet)',
        adet: 2,
        birimFiyat: 850,
        kdvOrani: 20,
        toplamTutar: 1700,
      },
      {
        id: 'ln_5',
        tur: 'Iscilik',
        tanim: 'OSB Fabrika Yerinde Arıza Tespiti & Yangın Sistem Revizyonu',
        adet: 1,
        birimFiyat: 2500,
        kdvOrani: 20,
        toplamTutar: 2500,
      },
    ],
    iscilikUcreti: 2500,
    parcaUcreti: 1700,
    kdvTutari: 840,
    indirimTutari: 0,
    toplamTutar: 5040,
    alinanKapora: 2000,
    kalanTutar: 3040,
    odemeTuru: 'HavaleEFT',
    tahsilEdildi: false,
    garantiKapsaminda: false,
    garantiSuresiAy: 12,
    oncelik: 'Kritik',
    dahiliNotlar: 'Fabrika müdürü Mehmet Bey teslim tutanağını imzaladı.',
  },

  // 3. İç Servis (Atölye) / Bilgisayar & Sunucu Donanım
  {
    id: 'srv_103',
    servisNo: 'DZA-2026-0103',
    musteriAdSoyad: 'Kemal ÖZKAN',
    musteriTelefon: '0(532) 998 77 66',
    musteriEmail: 'kemal.ozkan@gmail.com',
    servisTuru: 'IcServis',
    faaliyetAlani: 'Bilgisayar',
    islemTuru: 'ArizaCozum',
    cihazTipi: 'Laptop / Dizüstü Bilgisayar',
    markaModel: 'Lenovo ThinkPad P15 Gen 2 İş İstasyonu',
    seriNoImei: 'PF-28919024',
    cihazSifresi: '1923',
    aksesuarlar: ['Orijinal Adaptör', 'Çanta'],
    siviTemasi: false,
    ekranKirik: false,
    cizikVar: true,
    darbeVar: false,
    acilmiyor: false,
    sarjAlmiyor: false,
    asinIsinma: true,
    sesYok: false,
    kameraArizali: false,
    arizaTanimi: 'Mühendislik çizim programlarında render alırken aşırı ısınıp kapanıyor, açılışta fan hatası veriyor.',
    teknisyenTespit: 'Sol soğutma bloğu fan motoru sıkışmış, termal macun kurumuş.',
    yapilanIslemler: 'Orijinal çift fan bloğu takıldı, sıvı metal/termal pad yenilendi. Stres testi uygulandı.',
    fotograflar: [],
    durum: 'Tamamlandi',
    atananTeknisyenId: 'tech_3',
    atananTeknisyenAd: 'Caner USTA',
    gelisTarihi: '2026-09-06T10:00:00.000Z',
    tamamlanmaTarihi: '2026-09-07T11:00:00.000Z',
    satirlar: [
      {
        id: 'ln_6',
        tur: 'Parca',
        tanim: 'Lenovo ThinkPad P15 Orijinal Çift Soğutma Fan Modülü',
        adet: 1,
        birimFiyat: 1800,
        kdvOrani: 20,
        toplamTutar: 1800,
      },
      {
        id: 'ln_7',
        tur: 'Iscilik',
        tanim: 'Termal Bakım & Donanım Değişim İşçiliği',
        adet: 1,
        birimFiyat: 800,
        kdvOrani: 20,
        toplamTutar: 800,
      },
    ],
    iscilikUcreti: 800,
    parcaUcreti: 1800,
    kdvTutari: 520,
    indirimTutari: 120,
    toplamTutar: 3000,
    alinanKapora: 1000,
    kalanTutar: 2000,
    odemeTuru: 'Nakit',
    tahsilEdildi: false,
    garantiKapsaminda: false,
    garantiSuresiAy: 6,
    oncelik: 'Normal',
  },

  // 4. Dış Servis / Network & Yapısal Kablolama & Yazılım Desteği
  {
    id: 'srv_104',
    servisNo: 'DZA-2026-0104',
    musteriAdSoyad: 'Güven Hukuk & Danışmanlık Bürosu',
    musteriTelefon: '0(324) 238 12 34',
    musteriEmail: 'info@guvenhukuk.av.tr',
    musteriAdres: 'Çamlıbel Mah. Atatürk Parkı Karşısı No:12 Kat:3',
    servisTuru: 'DisServis',
    faaliyetAlani: 'Network',
    islemTuru: 'Teklif',
    teklifDurumu: 'Sunuldu',
    sahaAdresi: 'Çamlıbel Mah. Atatürk Parkı Karşısı No:12 Kat:3',
    sahaRandevuTarihi: '2026-09-08T14:00:00.000Z',
    sahaEkibi: 'Zafer GÖRGÜN',
    cihazTipi: 'Rack Kabin / Patch Panel / PDU',
    markaModel: 'Diza Yazılım SQL Sunucu & Ofis Gigabit Network Altyapısı',
    seriNoImei: 'NET-RACK-091',
    aksesuarlar: ['Kabin Anahtarları'],
    siviTemasi: false,
    ekranKirik: false,
    cizikVar: false,
    darbeVar: false,
    acilmiyor: false,
    sarjAlmiyor: false,
    asinIsinma: false,
    sesYok: false,
    kameraArizali: false,
    arizaTanimi: 'Ofis taşınması sonrası 8 avukat bilgisayarının Diza Yazılım muhasebe programına bağlanması, Gigabit ağ kablolaması ve Wi-Fi kapsama projesi.',
    teknisyenTespit: '9U Rack kabin kurulacak, Cat6 sonlandırma patch panel yapılacak, 1 adet tavan tipi Wi-Fi Access Point kurulacak.',
    fotograflar: [],
    durum: 'OnayBekliyor',
    atananTeknisyenId: 'tech_1',
    atananTeknisyenAd: 'Zafer GÖRGÜN',
    gelisTarihi: '2026-09-07T09:40:00.000Z',
    satirlar: [
      {
        id: 'ln_8',
        tur: 'Parca',
        tanim: '9U Duvar Tipi Cam Kapaklı Rack Kabin & PDU',
        adet: 1,
        birimFiyat: 2800,
        kdvOrani: 20,
        toplamTutar: 2800,
      },
      {
        id: 'ln_9',
        tur: 'Parca',
        tanim: 'Ruijie Reyee Wi-Fi 6 Tavan Tipi Access Point',
        adet: 1,
        birimFiyat: 3200,
        kdvOrani: 20,
        toplamTutar: 3200,
      },
      {
        id: 'ln_10',
        tur: 'Iscilik',
        tanim: 'Yapısal Kablolama, SQL Bağlantısı ve Diza Yazılım Kurulumu',
        adet: 1,
        birimFiyat: 5000,
        kdvOrani: 20,
        toplamTutar: 5000,
      },
    ],
    iscilikUcreti: 5000,
    parcaUcreti: 6000,
    kdvTutari: 2200,
    indirimTutari: 200,
    toplamTutar: 13000,
    alinanKapora: 3000,
    kalanTutar: 10000,
    odemeTuru: 'HavaleEFT',
    tahsilEdildi: false,
    garantiKapsaminda: false,
    garantiSuresiAy: 24,
    oncelik: 'Normal',
    dahiliNotlar: 'Fiyat teklifi hazırlandı ve WhatsApp üzerinden Avukat Caner Bey e gönderildi.',
  },

  // 5. Dış Servis / Hırsız Alarm Sistemi Arızası & Akü Değişimi
  {
    id: 'srv_105',
    servisNo: 'DZA-2026-0105',
    musteriAdSoyad: 'İnci Kuyumculuk',
    musteriTelefon: '0(533) 222 33 44',
    musteriEmail: 'incikuyumculuk@gmail.com',
    musteriAdres: 'Çarşı Kuyumcular Çarşısı No:19 Akdeniz / Mersin',
    servisTuru: 'DisServis',
    faaliyetAlani: 'AlarmSistemi',
    islemTuru: 'ArizaCozum',
    sahaAdresi: 'Kuyumcular Çarşısı No:19',
    sahaRandevuTarihi: '2026-09-07T16:00:00.000Z',
    sahaEkibi: 'Murat TEKNİK',
    cihazTipi: 'Hırsız Alarm Paneli',
    markaModel: 'DSC PowerSeries Neo Hibrit Alarm',
    seriNoImei: 'DSC-NEO-8831',
    aksesuarlar: ['Panel Anahtarı', 'Keypad'],
    siviTemasi: false,
    ekranKirik: false,
    cizikVar: false,
    darbeVar: false,
    acilmiyor: false,
    sarjAlmiyor: false,
    asinIsinma: false,
    sesYok: false,
    kameraArizali: false,
    arizaTanimi: 'Kuyumcu dükkanı alarmı elektrik kesilince susuyor, panel sarı arıza ışığı yakıyor, siren test edilemiyor.',
    teknisyenTespit: 'Panel 12V 7Ah kuru aküsü ve harici siren pili tamamen ömrünü tamamlamış.',
    yapilanIslemler: 'Orijinal 12V 7Ah Yuasa akü ve siren pili takıldı, GSM haberleşme merkezi test sinyali gönderildi.',
    fotograflar: [],
    durum: 'Tamamlandi',
    atananTeknisyenId: 'tech_2',
    atananTeknisyenAd: 'Murat TEKNİK',
    gelisTarihi: '2026-09-07T12:00:00.000Z',
    tamamlanmaTarihi: '2026-09-07T16:30:00.000Z',
    satirlar: [
      {
        id: 'ln_11',
        tur: 'Parca',
        tanim: '12V 7Ah Kuru Tip Bakımsız Alarm Paneli Aküsü',
        adet: 1,
        birimFiyat: 850,
        kdvOrani: 20,
        toplamTutar: 850,
      },
      {
        id: 'ln_12',
        tur: 'Iscilik',
        tanim: 'Kuyumcu Alarm Sistemi Periyodik Test & Akü Değişim Hizmeti',
        adet: 1,
        birimFiyat: 950,
        kdvOrani: 20,
        toplamTutar: 950,
      },
    ],
    iscilikUcreti: 950,
    parcaUcreti: 850,
    kdvTutari: 360,
    indirimTutari: 60,
    toplamTutar: 2100,
    alinanKapora: 2100,
    kalanTutar: 0,
    odemeTuru: 'Nakit',
    tahsilEdildi: true,
    garantiKapsaminda: false,
    garantiSuresiAy: 12,
    oncelik: 'Kritik',
  },

  // 6. Yazılım & Ön Muhasebe Desteği
  {
    id: 'srv_106',
    servisNo: 'DZA-2026-0106',
    musteriAdSoyad: 'Baran Mobilya & İnşaat Ltd.',
    musteriTelefon: '0(541) 333 44 55',
    servisTuru: 'IcServis',
    faaliyetAlani: 'Yazilim',
    islemTuru: 'MontajKurulum',
    teklifDurumu: 'Onaylandi',
    cihazTipi: 'Ticari Ön Muhasebe / SQL Veritabanı',
    markaModel: 'Diza Yazılım Ön Muhasebe & E-Fatura & Çoklu Şube',
    seriNoImei: 'DZA-LIC-2026-099',
    aksesuarlar: ['Yazılım Lisans Anahtarı'],
    siviTemasi: false,
    ekranKirik: false,
    cizikVar: false,
    darbeVar: false,
    acilmiyor: false,
    sarjAlmiyor: false,
    asinIsinma: false,
    sesYok: false,
    kameraArizali: false,
    arizaTanimi: 'İkinci şube için Diza Yazılım ticari ön muhasebe kullanıcı lisansı kurulumu, e-Fatura entegrasyonu ve personel eğitimi.',
    teknisyenTespit: 'SQL Server uzak bağlantı portu açıldı, lisans aktif edildi.',
    yapilanIslemler: 'Diza Yazılım istemci kurulumu yapıldı, barkodlu satış ekranı ve cari tanımları senkronize edildi.',
    fotograflar: [],
    durum: 'Tamamlandi',
    atananTeknisyenId: 'tech_1',
    atananTeknisyenAd: 'Zafer GÖRGÜN',
    gelisTarihi: '2026-09-07T14:15:00.000Z',
    tamamlanmaTarihi: '2026-09-07T16:00:00.000Z',
    satirlar: [
      {
        id: 'ln_13',
        tur: 'Parca',
        tanim: 'Diza Yazılım Ek Kullanıcı & E-Fatura Modülü Lisansı',
        adet: 1,
        birimFiyat: 8500,
        kdvOrani: 20,
        toplamTutar: 8500,
      },
      {
        id: 'ln_14',
        tur: 'Iscilik',
        tanim: 'Uzak Masaüstü Kurulum, Veritabanı Entegrasyonu & Eğitim',
        adet: 1,
        birimFiyat: 1500,
        kdvOrani: 20,
        toplamTutar: 1500,
      },
    ],
    iscilikUcreti: 1500,
    parcaUcreti: 8500,
    kdvTutari: 2000,
    indirimTutari: 0,
    toplamTutar: 12000,
    alinanKapora: 6000,
    kalanTutar: 6000,
    odemeTuru: 'HavaleEFT',
    tahsilEdildi: false,
    garantiKapsaminda: false,
    garantiSuresiAy: 12,
    oncelik: 'Normal',
  },
];

export const initialCashMoves: KasaHareketi[] = [
  {
    id: 'csh_1',
    tarih: '2026-09-06T09:00:00.000Z',
    islemTuru: 'Gelir',
    kategori: 'Kapora',
    aciklama: 'DZA-2026-0101 16 Kamera Montajı Kapora Tahsilatı (Toros Lojistik)',
    tutar: 25000,
    odemeTuru: 'HavaleEFT',
    servisId: 'srv_101',
    servisNo: 'DZA-2026-0101',
  },
  {
    id: 'csh_2',
    tarih: '2026-09-07T08:30:00.000Z',
    islemTuru: 'Gelir',
    kategori: 'Kapora',
    aciklama: 'DZA-2026-0102 Fabrika Yangın Alarmı Kapora Tahsilatı (Kuzey Tekstil)',
    tutar: 2000,
    odemeTuru: 'HavaleEFT',
    servisId: 'srv_102',
    servisNo: 'DZA-2026-0102',
  },
  {
    id: 'csh_3',
    tarih: '2026-09-07T16:35:00.000Z',
    islemTuru: 'Gelir',
    kategori: 'ServisTahsilat',
    aciklama: 'DZA-2026-0105 Kuyumcu Alarm Akü & Bakım Tam Tahsilatı (İnci Kuyumculuk)',
    tutar: 2100,
    odemeTuru: 'Nakit',
    servisId: 'srv_105',
    servisNo: 'DZA-2026-0105',
  },
  {
    id: 'csh_4',
    tarih: '2026-09-07T14:20:00.000Z',
    islemTuru: 'Gelir',
    kategori: 'Kapora',
    aciklama: 'DZA-2026-0106 Diza Yazılım Lisans & Kurulum Kapora (Baran Mobilya)',
    tutar: 6000,
    odemeTuru: 'HavaleEFT',
    servisId: 'srv_106',
    servisNo: 'DZA-2026-0106',
  },
];
