/**
 * Diza Teknik Servis — Gördit Bilgisayar
 * Copyright © 2024-2026 Gördit Bilgisayar — Zafer GÖRGÜN
 */

import type {
  TeknikServisItem,
  StokParca,
  Teknisyen,
  KasaHareketi,
  FirmaAyarlari,
} from '../types';

export const initialSettings: FirmaAyarlari = {
  firmaAdi: 'Diza Teknik Servis & Bilişim Hizmetleri',
  resmiUnvan: 'Gördit Bilgisayar — Zafer GÖRGÜN',
  telefon: '0(324) 233 00 00',
  gsm: '0(541) 608 53 44',
  email: 'bilgi@gorditbilgisayar.com',
  adres: 'İstiklal Caddesi No:42 Akdeniz / MERSİN',
  vergiDairesi: 'Uray Vergi Dairesi',
  vergiNo: '4110293841',
  webSitesi: 'https://www.gorditbilgisayar.com',
  servisSartlariA4: `1. Servisimize bırakılan cihazların arıza tespiti ücretsizdir. Müşteri onayı alınmadan ücretli tamir işlemine başlanmaz.
2. Servis süresi yasal olarak azami 20 iş günüdür. Parça temini gerektiren durumlarda müşteriye bilgi verilir.
3. Servisimize bırakılan cihazlarda oluşabilecek veri kayıplarından firmamız sorumlu değildir. Yedekleme sorumluluğu müşteriye aittir.
4. Tamiri tamamlanan veya iade edilen cihazlar, bilgilendirme tarihinden itibaren 30 gün içinde teslim alınmalıdır.
5. Yapılan donanımsal tamir ve parça değişimleri 6 ay firmamız garantisi altındadır (Sıvı teması ve darbe hariçtir).`,
  termalSartlar: `* 30 gün içinde teslim alınmayan cihazlardan firmamız sorumlu değildir.
* Veri yedekleme sorumluluğu müşteriye aittir.
* Donanım tamirlerimiz 6 ay garantilidir.
Gördit Bilgisayar — Zafer GÖRGÜN`,
  servisNoOnEk: 'TS',
  sonServisNo: 104,
};

export const initialTechnicians: Teknisyen[] = [
  {
    id: 'tech_1',
    adSoyad: 'Zafer GÖRGÜN',
    telefon: '0(541) 608 53 44',
    uzmanlik: 'Kıdemli Sistem & Donanım Uzmanı',
    aktif: true,
  },
  {
    id: 'tech_2',
    adSoyad: 'Murat TEKNİK',
    telefon: '0(532) 111 22 33',
    uzmanlik: 'Anakart BGA & SMD Onarım Uzmanı',
    aktif: true,
  },
  {
    id: 'tech_3',
    adSoyad: 'Caner USTA',
    telefon: '0(535) 444 55 66',
    uzmanlik: 'Akıllı Telefon & Tablet Teknisyeni',
    aktif: true,
  },
];

export const initialParts: StokParca[] = [
  {
    id: 'stk_1',
    kod: 'PRC-SSD-512',
    ad: 'Kingston NV2 512GB NVMe M.2 SSD',
    kategori: 'Depolama',
    stokAdedi: 14,
    kritikStok: 3,
    alisFiyati: 1100,
    satisFiyati: 1750,
    kdvOrani: 20,
  },
  {
    id: 'stk_2',
    kod: 'PRC-RAM-16D4',
    ad: 'Crucial 16GB DDR4 3200MHz Notebook RAM',
    kategori: 'Bellek',
    stokAdedi: 8,
    kritikStok: 2,
    alisFiyati: 950,
    satisFiyati: 1450,
    kdvOrani: 20,
  },
  {
    id: 'stk_3',
    kod: 'PRC-BAT-IP14',
    ad: 'iPhone 14 Pro Orijinal Kalite Batarya',
    kategori: 'Batarya',
    stokAdedi: 5,
    kritikStok: 2,
    alisFiyati: 1200,
    satisFiyati: 2100,
    kdvOrani: 20,
  },
  {
    id: 'stk_4',
    kod: 'PRC-SCR-L156',
    ad: '15.6" Full HD IPS Slim 30 Pin Laptop Ekranı',
    kategori: 'Ekran',
    stokAdedi: 6,
    kritikStok: 2,
    alisFiyati: 1800,
    satisFiyati: 2900,
    kdvOrani: 20,
  },
  {
    id: 'stk_5',
    kod: 'PRC-TC-GRZ',
    ad: 'Thermal Grizzly Kryonaut Yüksek Performans Macun',
    kategori: 'Sarf Malzeme',
    stokAdedi: 22,
    kritikStok: 5,
    alisFiyati: 220,
    satisFiyati: 450,
    kdvOrani: 20,
  },
];

export const initialServices: TeknikServisItem[] = [
  {
    id: 'srv_1',
    servisNo: 'TS-2026-0101',
    musteriAdSoyad: 'Ahmet YILMAZ',
    musteriTelefon: '0(532) 412 88 90',
    musteriEmail: 'ahmet.yilmaz@email.com',
    musteriAdres: 'Toroslar Mah. 201. Sok. No:12 Mersin',
    cihazTipi: 'Laptop / Dizüstü Bilgisayar',
    markaModel: 'Asus TUF Gaming FX506LH',
    seriNoImei: 'ASUS-TUF-88492019',
    cihazSifresi: '1923',
    kilitDeseni: [0, 1, 2, 5, 8],
    aksesuarlar: ['Orijinal Şarj Adaptörü', 'Taşıma Çantası'],
    siviTemasi: false,
    ekranKirik: false,
    cizikVar: true,
    darbeVar: false,
    acilmiyor: false,
    sarjAlmiyor: false,
    asinIsinma: true,
    sesYok: false,
    kameraArizali: false,
    fizikselDurumNotu: 'Üst kapakta hafif sürtünme izi mevcut, fanlardan aşırı ses geliyor.',
    arizaTanimi: 'Oyun oynarken cihaz aşırı ısınıyor ve 15 dakika sonra kendi kendine kapanıyor. Fanlar tam devirde dönüyor.',
    teknisyenTespit: 'Termal macun tamamen kurumuş, fan ızgaraları toz öbeğiyle tıkanmış. GPU ve CPU sıcaklığı 96°C.',
    yapilanIslemler: 'Termal blok söküldü, ultrasonik fan temizliği yapıldı, Thermal Grizzly termal macun yenilendi. 1 saatlik FurMark testinde max 72°C ölçüldü.',
    fotograflar: [],
    durum: 'Tamamlandi',
    atananTeknisyenId: 'tech_1',
    atananTeknisyenAd: 'Zafer GÖRGÜN',
    gelisTarihi: '2026-09-05T09:30:00.000Z',
    tamamlanmaTarihi: '2026-09-06T14:20:00.000Z',
    satirlar: [
      {
        id: 'ln_1',
        tur: 'Parca',
        tanim: 'Thermal Grizzly Kryonaut Yüksek Performans Macun',
        adet: 1,
        birimFiyat: 450,
        kdvOrani: 20,
        toplamTutar: 450,
      },
      {
        id: 'ln_2',
        tur: 'Iscilik',
        tanim: 'Detaylı Fan Temizliği & Termal Bakım İşçiliği',
        adet: 1,
        birimFiyat: 550,
        kdvOrani: 20,
        toplamTutar: 550,
      },
    ],
    iscilikUcreti: 550,
    parcaUcreti: 450,
    kdvTutari: 200,
    indirimTutari: 50,
    toplamTutar: 1150,
    alinanKapora: 300,
    kalanTutar: 850,
    odemeTuru: 'Nakit',
    tahsilEdildi: false,
    garantiKapsaminda: false,
    garantiSuresiAy: 6,
    oncelik: 'Normal',
    dahiliNotlar: 'Müşteri cumartesi günü teslim alacak.',
  },
  {
    id: 'srv_2',
    servisNo: 'TS-2026-0102',
    musteriAdSoyad: 'Elif KAYA',
    musteriTelefon: '0(542) 789 65 43',
    musteriEmail: 'elif.kaya@firma.com',
    cihazTipi: 'Akıllı Telefon / Cep Telefonu',
    markaModel: 'Apple iPhone 14 Pro 128GB',
    seriNoImei: '358291048192019',
    cihazSifresi: '2580',
    aksesuarlar: ['Kılıf'],
    siviTemasi: false,
    ekranKirik: true,
    cizikVar: true,
    darbeVar: true,
    acilmiyor: false,
    sarjAlmiyor: false,
    asinIsinma: false,
    sesYok: false,
    kameraArizali: false,
    fizikselDurumNotu: 'Sağ alt köşeden düşmüş, ön cam çatlak dokunmatik sağ kısımda basmıyor.',
    arizaTanimi: 'Yere düşme sonucu ön cam tuzla buz oldu, alt dokunmatik tepki vermiyor.',
    fotograflar: [],
    durum: 'OnayBekliyor',
    atananTeknisyenId: 'tech_3',
    atananTeknisyenAd: 'Caner USTA',
    gelisTarihi: '2026-09-06T11:15:00.000Z',
    satirlar: [
      {
        id: 'ln_3',
        tur: 'Parca',
        tanim: 'iPhone 14 Pro Orijinal OLED Ekran Değişimi',
        adet: 1,
        birimFiyat: 6800,
        kdvOrani: 20,
        toplamTutar: 6800,
      },
      {
        id: 'ln_4',
        tur: 'Iscilik',
        tanim: 'TrueTone Aktarımı ve Ekran Montaj İşçiliği',
        adet: 1,
        birimFiyat: 700,
        kdvOrani: 20,
        toplamTutar: 700,
      },
    ],
    iscilikUcreti: 700,
    parcaUcreti: 6800,
    kdvTutari: 1500,
    indirimTutari: 0,
    toplamTutar: 9000,
    alinanKapora: 1000,
    kalanTutar: 8000,
    odemeTuru: 'KrediKarti',
    tahsilEdildi: false,
    garantiKapsaminda: false,
    garantiSuresiAy: 6,
    oncelik: 'Acil',
    dahiliNotlar: 'Müşteriye WhatsApp üzerinden fiyat onayı gönderildi, onay bekleniyor.',
  },
  {
    id: 'srv_3',
    servisNo: 'TS-2026-0103',
    musteriAdSoyad: 'Mehmet ÖZTÜRK',
    musteriTelefon: '0(505) 321 44 55',
    cihazTipi: 'Masaüstü Bilgisayar (Kasa)',
    markaModel: 'Özel Toplama Oyun Bilgisayarı (Ryzen 5 / RTX 3060)',
    seriNoImei: 'PC-CUSTOM-7712',
    aksesuarlar: ['Güç Kablosu'],
    siviTemasi: false,
    ekranKirik: false,
    cizikVar: false,
    darbeVar: false,
    acilmiyor: true,
    sarjAlmiyor: false,
    asinIsinma: false,
    sesYok: false,
    kameraArizali: false,
    arizaTanimi: 'Elektrik kesintisinden sonra cihaz hiç tepki vermiyor, güç düğmesine basınca fanlar 1 saniye dönüp duruyor.',
    fotograflar: [],
    durum: 'Tamirde',
    atananTeknisyenId: 'tech_2',
    atananTeknisyenAd: 'Murat TEKNİK',
    gelisTarihi: '2026-09-07T08:45:00.000Z',
    satirlar: [
      {
        id: 'ln_5',
        tur: 'Parca',
        tanim: 'Anakart Besleme Mosfet & PWM Kontrolcü Onarımı',
        adet: 1,
        birimFiyat: 1400,
        kdvOrani: 20,
        toplamTutar: 1400,
      },
    ],
    iscilikUcreti: 600,
    parcaUcreti: 1400,
    kdvTutari: 400,
    indirimTutari: 0,
    toplamTutar: 2400,
    alinanKapora: 500,
    kalanTutar: 1900,
    odemeTuru: 'HavaleEFT',
    tahsilEdildi: false,
    garantiKapsaminda: false,
    garantiSuresiAy: 6,
    oncelik: 'Kritik',
    dahiliNotlar: 'Anakart SMD onarım masasında inceleniyor.',
  },
  {
    id: 'srv_4',
    servisNo: 'TS-2026-0104',
    musteriAdSoyad: 'Selin DEMİR',
    musteriTelefon: '0(533) 987 11 22',
    cihazTipi: 'Yazıcı / Tarayıcı / Fotokopi',
    markaModel: 'HP LaserJet Pro M404dn',
    seriNoImei: 'VNC3829104',
    aksesuarlar: ['Güç Kablosu', 'USB Kablosu'],
    siviTemasi: false,
    ekranKirik: false,
    cizikVar: false,
    darbeVar: false,
    acilmiyor: false,
    sarjAlmiyor: false,
    asinIsinma: false,
    sesYok: false,
    kameraArizali: false,
    arizaTanimi: 'Kağıt alırken takılıyor, silindir kağıdı yarıda bırakıyor ve sıkışma hatası veriyor.',
    fotograflar: [],
    durum: 'KabulEdildi',
    atananTeknisyenId: 'tech_1',
    atananTeknisyenAd: 'Zafer GÖRGÜN',
    gelisTarihi: '2026-09-07T10:20:00.000Z',
    satirlar: [],
    iscilikUcreti: 0,
    parcaUcreti: 0,
    kdvTutari: 0,
    indirimTutari: 0,
    toplamTutar: 0,
    alinanKapora: 0,
    kalanTutar: 0,
    tahsilEdildi: false,
    garantiKapsaminda: false,
    garantiSuresiAy: 3,
    oncelik: 'Normal',
  },
];

export const initialCashMoves: KasaHareketi[] = [
  {
    id: 'csh_1',
    tarih: '2026-09-05T09:35:00.000Z',
    islemTuru: 'Gelir',
    kategori: 'Kapora',
    aciklama: 'TS-2026-0101 Kapora Tahsilatı (Ahmet YILMAZ)',
    tutar: 300,
    odemeTuru: 'Nakit',
    servisId: 'srv_1',
    servisNo: 'TS-2026-0101',
  },
  {
    id: 'csh_2',
    tarih: '2026-09-06T11:20:00.000Z',
    islemTuru: 'Gelir',
    kategori: 'Kapora',
    aciklama: 'TS-2026-0102 Kapora Tahsilatı (Elif KAYA)',
    tutar: 1000,
    odemeTuru: 'KrediKarti',
    servisId: 'srv_2',
    servisNo: 'TS-2026-0102',
  },
  {
    id: 'csh_3',
    tarih: '2026-09-07T08:50:00.000Z',
    islemTuru: 'Gelir',
    kategori: 'Kapora',
    aciklama: 'TS-2026-0103 Kapora Tahsilatı (Mehmet ÖZTÜRK)',
    tutar: 500,
    odemeTuru: 'HavaleEFT',
    servisId: 'srv_3',
    servisNo: 'TS-2026-0103',
  },
];
